### ISSUE TITLE
feat: new eslint config

### ISSUE THREAD

**Issue by Sandros94** [Sandros94/nuxt-starters#2]
I'm not fully happy with my current eslint config, I should experiment with others from the community.

Some that captured my interest:
- [@antfu/eslint-config](https://github.com/antfu/eslint-config) (but I need to heavily customize it)
- [@stefanobartoletti/eslint-config](https://github.com/stefanobartoletti/eslint-config) (not tested yet)

**Comment by sandros94** [comment]
Currently testing stefano's config, will see if it how much customization I need or if I should create my own
